#!/bin/sh

find . -type f -name "*.css" ! -name "*.min.css" |
  while read f
    do
      dst="${f%.*}.min.css"
      echo "$f -> $dst"
      csso "$f" > "$dst"
      git add "$dst"
    done

exec git diff-index --check --cached HEAD --
